name: validate

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            echo "✔ Running Lint..."
            npm run lint
          else
            echo "⚠ No lint script found in package.json. Skipping..."
          fi

      - name: Run Type Check (if available)
        run: |
          if npm run | grep -q "type-check"; then
            echo "✔ Running Type Check..."
            npm run type-check
          else
            echo "⚠ No type-check script found in package.json. Skipping..."
          fi

      - name: Build Docusaurus
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus-build
          path: build
